// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(MyApplicationDbContext))]
    partial class MyApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domaine.MyEntities.Numero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Valeur")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Valeur")
                        .IsUnique();

                    b.ToTable("Numeros");
                });

            modelBuilder.Entity("Domaine.MyEntities.NumeroTirageLoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumeroId")
                        .HasColumnType("int");

                    b.Property<int>("TirageLotoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TirageLotoId");

                    b.HasIndex("NumeroId", "TirageLotoId")
                        .IsUnique();

                    b.ToTable("NumerosTiragesLoto");
                });

            modelBuilder.Entity("Domaine.MyEntities.TirageLoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("TiragesLoto");
                });

            modelBuilder.Entity("Domaine.MyEntities.NumeroTirageLoto", b =>
                {
                    b.HasOne("Domaine.MyEntities.Numero", null)
                        .WithMany("NumerosTiragesLoto")
                        .HasForeignKey("NumeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domaine.MyEntities.TirageLoto", null)
                        .WithMany("NumerosTiragesLoto")
                        .HasForeignKey("TirageLotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domaine.MyEntities.Numero", b =>
                {
                    b.Navigation("NumerosTiragesLoto");
                });

            modelBuilder.Entity("Domaine.MyEntities.TirageLoto", b =>
                {
                    b.Navigation("NumerosTiragesLoto");
                });
#pragma warning restore 612, 618
        }
    }
}
